Update message.ts
Chatie/wechaty pull request #1862
Opened 2019-10-08 12:06 UTC by su-chang

Implement toContact() method

## I'm submitting a...

```
[ ] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

_please describe the changes that you are making_

_for features, please describe how to use the new feature_

_please include a reference to an existing issue, if applicable_

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

2019-10-09 04:03 UTC, huan requested changes
Please get approvement from @windmemory before I can continue reviewing this PR.

And also remember to link to the related issue from here.

Thanks.

2019-10-09 04:03 UTC, huan commented on src/user/message.ts
> +    const contact = this.wechaty.Contact.load(contactId)
Add a `await contact.ready()` from here.

2019-10-09 06:09 UTC, windmemory requested changes

2019-10-10 01:50 UTC, su-chang commented
Related issue: https://github.com/Chatie/wechaty/issues/1855

2019-10-10 16:01 UTC, huan requested changes
Please update the `wechaty-puppet` version to 0.17 in  `package.json` so that this PR can test against to the latest version of the puppet abstract class.

See: 

https://github.com/Chatie/wechaty/blob/master/package.json#L101

2019-10-11 09:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Chatie/wechaty?pullRequest=1862) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Chatie/wechaty?pullRequest=1862) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: su-chang<br/>:x: 苏畅<br/><hr/>**苏畅** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Chatie/wechaty?pullRequest=1862) it.</sub>

2019-10-14 09:26 UTC, su-chang commented
@huan I think I need your help, "This branch has conflicts that must be resolved" but it need `write access`. Sorry for my poor git skills.

2019-10-29 05:36 UTC, closed without merging